tls:
  certificates:
    - certFile: /certs/vault.services.house.crt
      keyFile: /certs/vault.services.house.key
    - certFile: /certs/minio.services.house.crt
      keyFile: /certs/minio.services.house.key
    - certFile: /certs/minio-console.services.house.crt
      keyFile: /certs/minio-console.services.house.key
    - certFile: /certs/postgres.services.house.crt
      keyFile: /certs/postgres.services.house.key
