services:
  vault:
    labels:
      - traefik.enable=true
      - traefik.http.routers.vault.entrypoints=websecure
      - traefik.http.routers.vault.tls=true
      - traefik.http.routers.vault.rule=Host(`vault.services.house`)
      - traefik.http.services.vault.loadbalancer.server.port=8200
    image: docker.io/vault:1.12.2
    environment:
      - VAULT_ADDR=http://127.0.0.1:8200
    volumes:
      - /volume1/vault:/vault/file
      - ./config:/config
    cap_add:
      - IPC_LOCK
    command:
    - sh
    - -c
    - |
      tar -C /config -cf- . | tar -C /vault/config -xf- && \
      exec vault server -config /vault/config
    networks:
      - services
    restart: always

networks:
  services:
    external: true
